---
title: Addiction Weddings
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: prabintp@gmail.com
description: Addiction wedding is one of the best professional wedding photography
  team in kerala.
baseurl: http://addictionweddings.com
logoImagePath: images/wedding-photography.png
facebook_url: https://www.facebook.com/addictionweddings/
twitter_url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
paginate: 
paginate_path: blog/page:num
google_analytics: UA-67692152-1
