# Site settings
title: Addiction Weddings
email: prabintp@gmail.com
description: Addiction wedding is one of the best professional wedding photography tea in kerala.

baseurl: "http://addictionweddings.com" # the subpath of your site, e.g. /blog/

# url: "http://yourdomain.com" # the base hostname & protocol for your site

logoImagePath: "../images/wedding-photography.png"

facebook_url: "https://www.facebook.com/addictionweddings/"
twitter_url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"

google_analytics: UA-67692152-1
